services:
 
  db:

    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123' # Senha para o usuário root (administrador)
      MYSQL_DATABASE: 'Diet_db'          # Cria um banco de dados com este nome
      MYSQL_USER: 'admin'                 # Cria um usuário para a nossa aplicação
      MYSQL_PASSWORD: '12345'            # Define a senha para este usuário
      
    
    ports:
      - "3306:3306"
      
    # Define os volumes para persistir os dados
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data: